name: aoc-env
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - sympy
  - pylint
  - jupyter
  - tqdm
  - ruff
  - seaborn
  - networkx
  - pytest
  - scipy
  - numba
  - line_profiler
  